contexts:
  global:
    layers:
      base_layer_buildings:
        src: /assets/layers/base-layer_buildings_optimiert.svg
        initially_visible: true

      base_layer_river:
        src: /assets/layers/base-layer_river.svg 
        initially_visible: true
        
      base_layer_streets:
        src: /assets/layers/base-layer_streets.svg
        initially_visible: true

      base_layer_glow:
        src: /assets/layers/base-layer_buildings_optimiert.svg 
        icon: /assets/icons/default_icon.svg
        initially_visible: true

      critical_places:
        src: /assets/layers/flood/critical_sites.json
        icon: /assets/icons/critical_sites.svg
        poi_icon: /assets/icons/marker_poi.svg
        initially_visible: true

      population_density:
        src: /assets/layers/population_density.png
        icon: /assets/icons/population_density.svg
        initially_visible: false

  scenarios:
    flood:
      layers:
        flood_simulation:
          src: /assets/layers/flood/flood_simulation.json
          icon: /assets/icons/flood.svg
          slider_icon: /assets/icons/flood-slider.svg
          initially_visible: true

      roles:
        fire_brigade:
          layers:
            emergency_calls:
              src: /assets/layers/flood/emergency_calls.json
              icon: /assets/icons/emergency_calls.svg
              initially_visible: false

            social_media:
              src: /assets/layers/flood/emergency_calls.json # Placeholder as it's missing in the new structure
              icon: /assets/icons/social_media.svg
              initially_visible: false

        police:
          layers:
            social_media:
              src: /assets/layers/flood/emergency_calls.json # Placeholder
              icon: /assets/icons/social_media.svg
              initially_visible: false

            evacuation_zones:
              src: /assets/layers/flood/evacuation_zones.svg
              icon: /assets/icons/default_icon.svg
              initially_visible: false

        crisis_staff:
          layers:
            social_media:
              src: /assets/layers/flood/emergency_calls.json # Placeholder
              icon: /assets/icons/social_media.svg
              initially_visible: false

    blackout:
      layers: {}
      roles: {}

    mass_event:
      layers: {}
      roles: {}
