# yaml-language-server: $schema=../schemas/layers.schema.json
layer_types:
  - id: static_image
    type: static-image
    interaction: none

  - id: locations
    type: locations
    interaction: inspect-location
    icon_mode: per-location

  - id: area_overlay
    type: areas
    interaction: inspect-area

  - id: lottie_sequence
    type: lottie-sequence
    interaction: timeline
    playback_control: true

  - id: pulsing_overlay
    type: pulsing-image
    interaction: inspect-area

  - id: png_sequence
    type: png-sequence
    interaction: timeline
    playback_control: true

  - id: svg_sequence
    type: svg-sequence
    interaction: timeline
    playback_control: true
