story_points:
  - id: intro
    type: quiz
    title_key: crises_challange.intro.title
    question_key: crises_challange.intro.question
    options:
      - label_key: crises_challange.intro.optionA
        value: a
      - label_key: crises_challange.intro.optionB
        value: b
    solution: ['b']
    next:
      right: free-coord-selection
      wrong: fail-screen
    minAnswers: 1
    maxAnswers: 1
    step: 1
    total_steps: 4

  - id: free-coord-selection
    type: location-quiz
    title_key: crises_challange.location.title
    question_key: crises_challange.location.question
    target: "#layers"
    activeLayerId: drone_feed
    solution:
      x: 1960
      y: 1500
    maxDistance: 800
    step: 2
    total_steps: 4
    success_screen:
      title_key: crises_challange.success_interlude.title
      description_key: crises_challange.success_interlude.description
      duration_ms: 900
    next:
      right: select-drone-drop-off
      wrong: fail-screen

  - id: select-drone-drop-off
    type: point-selection-quiz
    title_key: crises_challange.location.title
    question_key: crises_challange.location.question_detail
    target: "#layer-critical_places"
    selector: ".poi-marker"
    activeLayerId: critical_places
    # usesResultFrom: free-coord-selection (Logic will look at previous point's result)
    solution: ['critical_site_2']

    success_screen:
      title_key: crises_challange.success_interlude.title
      description_key: crises_challange.success_interlude.description
      duration_ms: 900
    next:
      right: quiz-who-you-wanna-call
      wrong: fail-screen
    minSelection: 1
    maxSelection: 1
    step: 3
    total_steps: 4

  - id: quiz-who-you-wanna-call
    type: quiz
    title_key: crises_challange.call.title
    question_key: crises_challange.call.question
    options:
      - label_key: crises_challange.call.optionA
        value: a
      - label_key: crises_challange.call.optionB
        value: b
      - label_key: crises_challange.call.optionC
        value: c
    solution: ['c']
    next:
      right: win-screen
      wrong: fail-screen
    minAnswers: 1
    maxAnswers: 1
    step: 4
    total_steps: 4

  - id: win-screen
    type: info
    title_key: crises_challange.win.title
    description_key: crises_challange.win.description
    continue_button_key: crises_challange.common.restart
    terminalStatus: passed
    next: intro

  - id: fail-screen
    type: info
    title_key: crises_challange.fail.title
    description_key: crises_challange.fail.description
    continue_button_key: crises_challange.common.restart
    terminalStatus: failed
    next: intro

